---
- hosts: localhost
  connection: local
  tasks:
    - name: "Create container"
      docker_container:
        name: "test_issue_library"
        image: centos:7
        recreate: true

    - add_host:
        name: test_issue_library
        ansible_connection: docker

- hosts: localhost
  connection: local
  roles:
    - roles/test
