---
- hosts: localhost
  connection: local
  tasks:

    - add_host:
        name: test_issue_library
        ansible_connection: docker

- hosts: localhost
  connection: local
  roles:
    - roles/test
