---
driver:
  name: docker
platforms:
  - name: molecule-issue-1803
    image: centos:7
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    create: create.yml
    converge: playbook.yml
    destroy: destroy.yml
scenario:
  name: default
